# Generated by Django 4.1.7 on 2023-04-13 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit_hash", models.CharField(max_length=128)),
                ("build_number", models.PositiveIntegerField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major", models.PositiveIntegerField()),
                ("minor", models.PositiveIntegerField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "series",
            },
        ),
        migrations.AddConstraint(
            model_name="series",
            constraint=models.UniqueConstraint(
                fields=("major", "minor"), name="major_minor_unique"
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="build_number_manager.series",
            ),
        ),
        migrations.AddConstraint(
            model_name="build",
            constraint=models.UniqueConstraint(
                fields=("series", "commit_hash"), name="commit_unique_in_series"
            ),
        ),
    ]
